name: Watch yt-dlp releases

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest release
        id: check
        run: |
          latest_release=$(curl -s "https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest" | jq -r .tag_name)
          echo "Latest release: $latest_release"
          
      - name: Trigger build workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: yt-dlp-release
